### ISSUE TITLE
[`semester-upkeep`] Enable YAML control of Kaggle's GPU setting

### ISSUE THREAD

**Issue by ionlights** [ucfai/bot#30]
Just a note, when referring to `groups`... `groups := {intelligence, core, data-science, supplementary}`

# Feature Request, for `autobot`
**Description** Not all Kaggle Kernels need GPUs. More importantly, Kaggle limits us to 2 active GPU Kernels, while we're allowed up to 10 CPU Kernels. Based on this, it makes sense to toggle GPUs from `syllabus.yml` – this also allows for toggling the meeting's info if there's a need to rapidly iterate on the Kaggle Kernel.

## Needs
- [ ] Follow the parameter settings and toggle GPU usage

## Initial Comments
`syllabus.yml` specifies all the parameters needed for a given meeting's setup. Within `syllabus.yml`, one should find...
```yaml
- required:
    # ... lots going on here
  optional:
    # ... lots going on here
    kaggle:
      datasets: []
      competitions: []
      kernels: []
      gpu: true  # <- pay attention to this
```
You'll want to make sure that this parameter is both **parsed** and later propagated to a meeting's `kernel-metadata.json` file – the template file is [here](../blob/master/autobot/templates/seed/meeting/kernel-metadata.json):
```json
{
    "id": "ucfaibot/{{ slug }}",
    "title": "{{ slug }}",
    "code_file": "{{ notebook }}.ipynb",
    "language": "python",
    "kernel_type": "notebook",
    "is_private": false,
    "enable_gpu": false,
    "enable_internet": true,
    "dataset_sources": {{ kaggle.datasets }},
    "competition_sources": {{ kaggle.competitions }},
    "kernel_sources": {{ kaggle.kernels }}
}
```
